language: java
sudo: false
jdk: oraclejdk7

install: true
script: mvn install -B -e -V -Dmaven.test.redirectTestOutputToFile=false

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
