language: java
sudo: false
jdk: openjdk11
install: true
script: ./travis.sh

notifications:
  email: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar

notifications:
  email: false
  webhooks:
    - secure: "DTZxNqT4nihDhVRl49rkFZpmWVrR2bHjMWROAzQ9HObcFCILj09zzCqp5+HRZNdQobOkCWAf6V8cK2QGJ+GhSWySxcIZv6up0Hh9le2SDEe3Bk9wcHFM/l1nSiCyhc4WGe0X4h8EW9tGs9o0Hu5+xNUiQ45/yYjZvXm0q6TwRjEObFfC1WlvwV5W5Ndu9BWv6YENHyodrlBVYfZbIuY8BB1kxmBTw1aIiclu483i8mLxcSempso4iONl/OgCYax0GCS8EGxHWurpSxyIyg6pTRUTHocidQ6j4LrrTK8QYEI+D6CJAHpYYgwb+GKXie9lQD06qsGoYZYcRreZeA4WwYjD2nv6rbSx1u7ss3RUxI7EkX4jXLIKQJ4t8z5ViXGrsB97856iMZaSXR6sBLwtXu61TY7W3AZCweEiPrXa8TWlqnGIwq5zLHB8mA5sKrnT/2CkRaDOYIc8/CDabB9wL30k33JG4kDIHOlr+umJyuGtIxIzmT8DyFstp30fJUlBJORcJd1nfjNTXIdrVKeJhjEQnlmluqj1UeP+0H0BfWWTHrsaYSsfvumH2W5IRXPEG8i+PUZF+c9el245vdhzWy4cxAPEvrqsXEGiOpDrf7DBDnQb2Jqg5/Mel6NFP/IcdofYX8OtTeHWCNxRPF6PfWsccQaxbasWnZuO62ElKMU="
  on_start: always
