language: java
sudo: false
jdk: oraclejdk7

install: mvn install -DskipTests=true
script: mvn test -Dmaven.test.redirectTestOutputToFile=false

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
