name: Build
on:
  push:
    branches:
      - master
      - branch-*
  pull_request:
  merge_group:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}
    runs-on: sonar-xs-public
    name: Build
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
        with:
          version: 2025.7.12
      - uses: SonarSource/ci-github-actions/get-build-number@4ef2061ff3c9dc144a66f8a6e480d04d2d79e3bb # v1.3.25
      - uses: SonarSource/ci-github-actions/build-maven@4ef2061ff3c9dc144a66f8a6e480d04d2d79e3bb # v1.3.25
        with:
          deploy-pull-request: ${{ github.event_name != 'workflow_call' }}
          artifactory-reader-role: private-reader
          artifactory-deployer-role: qa-deployer
          use-develocity: true

  promote:
    if: github.event_name != 'workflow_call'
    needs: [build]
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}
    runs-on: sonar-xs-public
    name: Promote
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
        with:
          cache_save: false
          version: 2025.7.12
      - uses: SonarSource/ci-github-actions/get-build-number@4ef2061ff3c9dc144a66f8a6e480d04d2d79e3bb # v1.3.25
      - uses: SonarSource/ci-github-actions/promote@4ef2061ff3c9dc144a66f8a6e480d04d2d79e3bb # v1.3.25
        with:
          promote-pull-request: true
