 
name: sonar-release
# This workflow is triggered when publishing a new github release
on: 
  release:
    types:
      - published

jobs:
  sonar_release:
    runs-on: ubuntu-latest
    name: Start release process
    steps:
      - name: Checkout release action
        uses: actions/checkout@v2
        with:
          repository: SonarSource/gh-action_LT_release

      - name: release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        # Put your action repo here
        uses: SonarSource/gh-action_LT_release@master

      - name: Check outputs
        if: always()
        run: |
          echo "${{ steps.lt_release.outputs.releasability }}"
          echo "${{ steps.lt_release.outputs.release }}"
