name: Scan Project on Demand

permissions:
  id-token: write
  contents: read
  pull-requests: read
  statuses: read  # To retrieve the BuildNumber
  checks: read # To use the wait-for-required-github-checks-run action

on:
  schedule:
    - cron: '20 3 * * *'
  workflow_dispatch:
    inputs:
      github_environment:
        description: Github Environment
        required: false
        type: string
        default: "ManualInvocation"
      runner_label:
        description: Github Action runner
        required: false
        type: string
        default: "sonar-runner-on-demand"

jobs:
  sonar-scan-complete:
    name: "sonar-scan-complete"
    runs-on: github-ubuntu-latest-m
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: jdx/mise-action@bfb9fa0b029db830a8c570757cee683df207a6c5 # v2.4.0
        with:
          version: 2025.7.12
      - uses: SonarSource/ci-github-actions/get-build-number@v1
      - uses: SonarSource/ci-github-actions/build-maven@v1
        env:
          DEVELOCITY_ACCESS_KEY: develocity.sonar.build=${{ env.DEVELOCITY_TOKEN }}
        with:
          deploy-pull-request: true
          artifactory-reader-role: private-reader
          artifactory-deployer-role: qa-deployer
          use-develocity: true
      - name: Get sonar token from Vault
        id: secrets
        uses: SonarSource/vault-action-wrapper@0a07dc6f71d7c76cb16cf8aced480c679ba05ef0
        with:
          secrets: |
            development/kv/data/next token | SONAR_NEXT_TOKEN;
            development/kv/data/sonarqube-us token | SONAR_SQC_US_TOKEN;
            development/kv/data/sonarcloud token | SONAR_SQC_EU_TOKEN;
      - name: Install Sonar Scanner
        run: |
          mkdir -p $GITHUB_WORKSPACE/sonar-scanner
          cd $GITHUB_WORKSPACE
          curl -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.1.0.4889-linux-x64.zip --output sonar-scanner.zip
          unzip sonar-scanner.zip
          mv sonar-scanner-7.1.0.4889-linux-x64/* sonar-scanner/
          rm -f sonar-scanner.zip
          chmod +x $GITHUB_WORKSPACE/sonar-scanner/bin/sonar-scanner
          echo "$GITHUB_WORKSPACE/sonar-scanner/bin" >> $GITHUB_PATH
        shell: bash
      - name: Run Sonar SQS Scan
        run: |
          chmod +x ./.github/scan.sh
          ./.github/scan.sh
        env:
          SONAR_HOST_URL: "https://next.sonarqube.com/sonarqube"
          PROJECT_KEY: "org.sonarsource.orchestrator:orchestrator-parent"
          SONAR_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).SONAR_NEXT_TOKEN }}
      - name: Run Sonar SQC US Scan
        run: |
          chmod +x ./.github/scan.sh
          ./.github/scan.sh
        env:
          SONAR_HOST_URL: "https://sonarqube.us"
          PROJECT_KEY: "SonarSource_orchestrator"
          SONAR_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).SONAR_SQC_US_TOKEN }}
      - name: Run Sonar SQC EU Scan
        run: |
          chmod +x ./.github/scan.sh
          ./.github/scan.sh
        env:
          SONAR_HOST_URL: "https://sonarcloud.io"
          PROJECT_KEY: "SonarSource_orchestrator"
          SONAR_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).SONAR_SQC_EU_TOKEN }}